name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    name: Build 3DSCraft .cia/.3dsx
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup environment
        run: |
          sudo chmod 777 tools/*
          sudo chmod +x tools/*
      - name: Clone and Build makerom
        run: |
          sudo apt-get update
          sudo apt-get install g++ gcc make wget tar -y

          git clone https://github.com/3DSGuy/Project_CTR
          cd Project_CTR
          
          make progs

          mkdir -p ../tools
          cp makerom/bin/makerom ../tools/
          cd ..
      - name: Build game code
        id: build
        run: |
          make
      - name: Upload 3DSX
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: 3DSCraft.3dsx
          path: |
            ./3DSCraft.3dsx
      - name: Upload CIA
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: 3DSCraft.cia
          path: |
            ./3DSCraft.cia
